name: Print various contexts while executing a workflow

on:
  pull_request:

  push:

  workflow_dispatch:

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print GitHub context'
        run: echo "${{ toJSON(github) }}"

      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"