name: Print various contexts while executing a workflow 2

on:
  pull_request:

  push:

  workflow_dispatch:

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Event context
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$EVENT_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
      - name: Output some defined settings 2
        env:
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REF_TYPE: ${{ github.ref_type }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          GITHUB_PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          GITHUB_EVENT_AFTER_SHA: ${{ github.event.after }}
          GITHUB_EVENT_BEFORE_SHA: ${{ github.event.before }}
        run: |
          echo "Action Name is $GITHUB_ACTION"
          echo "Actor is $GITHUB_ACTOR"
          echo "Base Ref is $GITHUB_BASE_REF"
          echo "Head Ref is $GITHUB_HEAD_REF"
          echo "Triggering Ref is $GITHUB_REF"
          echo "Triggering Ref Name is $GITHUB_REF_NAME"
          echo "Event Name is $GITHUB_EVENT_NAME"
          echo "Event Action is $GITHUB_EVENT_ACTION"
          echo "Ref Type is $GITHUB_REF_TYPE"
          echo "Repository is $GITHUB_REPOSITORY"
          echo "SHA is $GITHUB_SHA"
          echo "Triggering Actor is $GITHUB_TRIGGERING_ACTOR"
          echo "PR Base Ref is $GITHUB_PR_BASE_REF"
          echo "After-SHA is $GITHUB_EVENT_AFTER_SHA"
          echo "Before-SHA is $GITHUB_EVENT_BEFORE_AHS"
      - name: 'Is it a `Pull`-request?'
        id: is-pr
        shell: bash
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "is-pr=${{ env.GITHUB_EVENT_NAME == 'pull_request' }}" >> $GITHUB_OUTPUT
